name: Audit

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]


jobs:
  audit:
    name: npm Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: npm Audit
        run: npm i --package-lock-only && npm audit --json > audit-npm.json
        if: always()

      - name: Bandit check
        uses: jpetrucciani/bandit-check@main
        with:
          path: '.'
          bandit_flags: '-o audit-bandit.json -f json'
        if: always()

      - name: Upload npm Audit Reports
        uses: actions/upload-artifact@v3
        with:
          name: audit-npm.json
          path: audit-npm.json
        if: always()

      - name: Upload Bandit Audit Reports
        uses: actions/upload-artifact@v3
        with:
          name: audit-bandit.json
          path: audit-bandit.json
        if: always()
