name: Audit

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]


jobs:
  audit:
    name: npm Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Audit
        run: npm i --package-lock-only && npm audit
